FROM python:3.10-slim

RUN apt-get update && \
    apt-get install -y iputils-ping curl default-mysql-client netcat-openbsd && \
    rm -rf /var/lib/apt/lists/*


WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY backend/ ./backend
COPY wait-for-mysql.sh ./
RUN chmod +x wait-for-mysql.sh

ENV TZ=Asia/Shanghai

CMD ["./wait-for-mysql.sh", "mysql", "python", "backend/scheduler.py"]
