FROM python:3.10-slim

WORKDIR /app

# ⭐ 关键：安装 netcat
RUN apt-get update && apt-get install -y netcat-openbsd && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN chmod +x wait-for-mysql.sh

EXPOSE 5000

CMD ["python", "backend/app.py"]
